#!/usr/bin/env node
// The marketplace, locally. MIT.
//
//   npm run site            http://localhost:4173
//   PORT=5000 npm run site
//
// No dependencies and no build step, matching how meckie.ai itself is served
// (marketing-server.js + static HTML). Everything it serves is a real file in
// this repo, so what you see locally is what a visitor would get.
//
// Routes:
//   /                             catalog
//   /body/<slug>                  body page
//   /contribute                   how to submit one
//   /bodies.json                  the catalog feed Hangar Bay reads
//   /api/bodies/<slug>/template   the known template, as JSON
//   /api/bodies/<slug>/stl.zip    every STL for one body, zipped on the fly
//   /packs/...                    the packs themselves (viewers, briefs, STLs)

const http = require('http');
const fs = require('fs');
const path = require('path');
const P = require('./lib/packs');
const { zipOf } = require('./lib/zip');

const PORT = Number(process.env.PORT || 4173);
const SITE = path.join(P.ROOT, 'site');

const TYPES = {
  '.html': 'text/html; charset=utf-8', '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8', '.mjs': 'text/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8', '.svg': 'image/svg+xml',
  '.png': 'image/png', '.jpg': 'image/jpeg', '.webp': 'image/webp',
  '.stl': 'model/stl', '.csv': 'text/csv; charset=utf-8',
  '.yaml': 'text/yaml; charset=utf-8', '.txt': 'text/plain; charset=utf-8',
  '.md': 'text/markdown; charset=utf-8', '.zip': 'application/zip',
};

const send = (res, code, body, type = 'text/plain; charset=utf-8', extra = {}) => {
  res.writeHead(code, Object.assign({ 'Content-Type': type }, extra));
  res.end(body);
};

// Serve a file, refusing anything that climbs out of its root.
function sendFile(res, root, rel) {
  const full = path.resolve(root, '.' + path.posix.resolve('/', rel));
  if (!full.startsWith(path.resolve(root))) return send(res, 403, 'forbidden');
  let st;
  try { st = fs.statSync(full); } catch (e) { return send(res, 404, 'not found'); }
  if (st.isDirectory()) return sendFile(res, root, path.posix.join(rel, 'index.html'));
  const type = TYPES[path.extname(full).toLowerCase()] || 'application/octet-stream';
  res.writeHead(200, { 'Content-Type': type, 'Content-Length': st.size, 'Cache-Control': 'no-cache' });
  fs.createReadStream(full).pipe(res);
}

// The known template is generated by tools/site-data.js, so it is parsed from
// YAML exactly once and every consumer just serves the file.
function templateJson(slug) {
  return fs.readFileSync(path.join(P.ROOT, 'site', 'data', `${slug}.template.json`), 'utf8');
}

const server = http.createServer((req, res) => {
  const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`);
  const p = decodeURIComponent(url.pathname);
  const slugs = P.slugs();

  // Hangar Bay reads this to list official bodies in its picker. CORS is open
  // on purpose: the whole point is that another local app can fetch it.
  if (p === '/bodies.json') {
    const cat = JSON.parse(fs.readFileSync(path.join(P.ROOT, 'site', 'data', 'index.json'), 'utf8'));
    const origin = `http://${req.headers.host || `localhost:${PORT}`}`;
    cat.bodies = cat.bodies.map(b => Object.assign({}, b, {
      template_url: `${origin}/api/bodies/${b.slug}/template`,
      page_url: `${origin}/body/${b.slug}`,
      thumbnail_url: `${origin}/packs/${b.slug}/${path.basename(b.viewer)}?view=iso&embed=1`,
    }));
    return send(res, 200, JSON.stringify(cat, null, 2), TYPES['.json'],
      { 'Access-Control-Allow-Origin': '*' });
  }

  let m = /^\/api\/bodies\/([a-z0-9-]+)\/template$/.exec(p);
  if (m && slugs.includes(m[1])) {
    return send(res, 200, templateJson(m[1]), TYPES['.json'],
      { 'Access-Control-Allow-Origin': '*' });
  }

  m = /^\/api\/bodies\/([a-z0-9-]+)\/stl\.zip$/.exec(p);
  if (m && slugs.includes(m[1])) {
    const dir = path.join(P.packDir(m[1]), 'stl');
    const files = fs.readdirSync(dir).filter(f => f.endsWith('.stl')).sort().map(f => ({
      name: `${m[1]}/${f}`, data: fs.readFileSync(path.join(dir, f)), mtime: fs.statSync(path.join(dir, f)).mtime,
    }));
    const zip = zipOf(files);
    return send(res, 200, zip, TYPES['.zip'],
      { 'Content-Disposition': `attachment; filename="${m[1]}-stl.zip"` });
  }

  // The packs themselves: viewers, briefs, STLs, CSVs, manifests.
  if (p.startsWith('/packs/')) return sendFile(res, P.BODIES, p.slice('/packs'.length));

  // Pages. Query and hash carry the state, so these are static files.
  if (p === '/' || p === '/index.html') return sendFile(res, SITE, '/index.html');
  if (p === '/contribute' || p === '/contribute/') return sendFile(res, SITE, '/contribute.html');
  m = /^\/body\/([a-z0-9-]+)\/?$/.exec(p);
  if (m) {
    if (!slugs.includes(m[1])) return send(res, 404, 'no such body');
    return sendFile(res, SITE, '/body.html');
  }

  return sendFile(res, SITE, p);
});

server.listen(PORT, () => {
  console.log(`\n  Meckie bodies — the marketplace, locally`);
  console.log(`  http://localhost:${PORT}\n`);
  console.log(`  catalog feed   http://localhost:${PORT}/bodies.json`);
  console.log(`  a template     http://localhost:${PORT}/api/bodies/scout/template\n`);
});
